/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OAuth2 Authorization Server API
 * OAuth2 Authorization Server for Compta microservices. Provides token issuance and user authentication.
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/vue-query";
import type {
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationReturnType,
  UseQueryOptions,
  UseQueryReturnType,
} from "@tanstack/vue-query";

import { computed, unref } from "vue";
import type { MaybeRef } from "vue";

import type {
  ClientResponse,
  CreateClientRequest,
  GetAllClients200,
  RotateClientSecret200,
  UpdateClientRequest,
} from "../generated.schemas";

import { customInstance } from "../../../../api/axios-instance";
import type { ErrorType, BodyType } from "../../../../api/axios-instance";

/**
 * Retrieve a specific OAuth2 client by its client ID
 * @summary Get OAuth2 client by ID
 */
export const getClientById = (
  clientId: MaybeRef<string>,
  signal?: AbortSignal,
) => {
  clientId = unref(clientId);

  return customInstance<ClientResponse>({
    url: `/api/clients/${clientId}`,
    method: "GET",
    signal,
  });
};

export const getGetClientByIdQueryKey = (clientId?: MaybeRef<string>) => {
  return ["api", "clients", clientId] as const;
};

export const getGetClientByIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getClientById>>,
  TError = ErrorType<unknown>,
>(
  clientId: MaybeRef<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getClientById>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = getGetClientByIdQueryKey(clientId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getClientById>>> = ({
    signal,
  }) => getClientById(clientId, signal);

  return {
    queryKey,
    queryFn,
    enabled: computed(() => !!unref(clientId)),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getClientById>>,
    TError,
    TData
  >;
};

export type GetClientByIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getClientById>>
>;
export type GetClientByIdQueryError = ErrorType<unknown>;

/**
 * @summary Get OAuth2 client by ID
 */

export function useGetClientById<
  TData = Awaited<ReturnType<typeof getClientById>>,
  TError = ErrorType<unknown>,
>(
  clientId: MaybeRef<string>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getClientById>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetClientByIdQueryOptions(clientId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * Update an existing OAuth2 client
 * @summary Update OAuth2 client
 */
export const updateClient = (
  clientId: MaybeRef<string>,
  updateClientRequest: MaybeRef<UpdateClientRequest>,
) => {
  clientId = unref(clientId);
  updateClientRequest = unref(updateClientRequest);

  return customInstance<ClientResponse>({
    url: `/api/clients/${clientId}`,
    method: "PUT",
    headers: { "Content-Type": "application/json" },
    data: updateClientRequest,
  });
};

export const getUpdateClientMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateClient>>,
    TError,
    { clientId: string; data: BodyType<UpdateClientRequest> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateClient>>,
  TError,
  { clientId: string; data: BodyType<UpdateClientRequest> },
  TContext
> => {
  const mutationKey = ["updateClient"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateClient>>,
    { clientId: string; data: BodyType<UpdateClientRequest> }
  > = (props) => {
    const { clientId, data } = props ?? {};

    return updateClient(clientId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateClientMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateClient>>
>;
export type UpdateClientMutationBody = BodyType<UpdateClientRequest>;
export type UpdateClientMutationError = ErrorType<unknown>;

/**
 * @summary Update OAuth2 client
 */
export const useUpdateClient = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateClient>>,
      TError,
      { clientId: string; data: BodyType<UpdateClientRequest> },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof updateClient>>,
  TError,
  { clientId: string; data: BodyType<UpdateClientRequest> },
  TContext
> => {
  const mutationOptions = getUpdateClientMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Delete an OAuth2 client
 * @summary Delete OAuth2 client
 */
export const deleteClient = (clientId: MaybeRef<string>) => {
  clientId = unref(clientId);

  return customInstance<void>({
    url: `/api/clients/${clientId}`,
    method: "DELETE",
  });
};

export const getDeleteClientMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteClient>>,
    TError,
    { clientId: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteClient>>,
  TError,
  { clientId: string },
  TContext
> => {
  const mutationKey = ["deleteClient"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteClient>>,
    { clientId: string }
  > = (props) => {
    const { clientId } = props ?? {};

    return deleteClient(clientId);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteClientMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteClient>>
>;

export type DeleteClientMutationError = ErrorType<unknown>;

/**
 * @summary Delete OAuth2 client
 */
export const useDeleteClient = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteClient>>,
      TError,
      { clientId: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof deleteClient>>,
  TError,
  { clientId: string },
  TContext
> => {
  const mutationOptions = getDeleteClientMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Retrieve all registered OAuth2 clients
 * @summary Get all OAuth2 clients
 */
export const getAllClients = (signal?: AbortSignal) => {
  return customInstance<GetAllClients200>({
    url: `/api/clients`,
    method: "GET",
    signal,
  });
};

export const getGetAllClientsQueryKey = () => {
  return ["api", "clients"] as const;
};

export const getGetAllClientsQueryOptions = <
  TData = Awaited<ReturnType<typeof getAllClients>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getAllClients>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = getGetAllClientsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllClients>>> = ({
    signal,
  }) => getAllClients(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAllClients>>,
    TError,
    TData
  >;
};

export type GetAllClientsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAllClients>>
>;
export type GetAllClientsQueryError = ErrorType<unknown>;

/**
 * @summary Get all OAuth2 clients
 */

export function useGetAllClients<
  TData = Awaited<ReturnType<typeof getAllClients>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAllClients>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAllClientsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = unref(queryOptions).queryKey as DataTag<
    QueryKey,
    TData,
    TError
  >;

  return query;
}

/**
 * Create a new OAuth2 registered client
 * @summary Create a new OAuth2 client
 */
export const createClient = (
  createClientRequest: MaybeRef<CreateClientRequest>,
  signal?: AbortSignal,
) => {
  createClientRequest = unref(createClientRequest);

  return customInstance<ClientResponse>({
    url: `/api/clients`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: createClientRequest,
    signal,
  });
};

export const getCreateClientMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createClient>>,
    TError,
    { data: BodyType<CreateClientRequest> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createClient>>,
  TError,
  { data: BodyType<CreateClientRequest> },
  TContext
> => {
  const mutationKey = ["createClient"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createClient>>,
    { data: BodyType<CreateClientRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return createClient(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateClientMutationResult = NonNullable<
  Awaited<ReturnType<typeof createClient>>
>;
export type CreateClientMutationBody = BodyType<CreateClientRequest>;
export type CreateClientMutationError = ErrorType<unknown>;

/**
 * @summary Create a new OAuth2 client
 */
export const useCreateClient = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createClient>>,
      TError,
      { data: BodyType<CreateClientRequest> },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof createClient>>,
  TError,
  { data: BodyType<CreateClientRequest> },
  TContext
> => {
  const mutationOptions = getCreateClientMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Generate a new client secret for an OAuth2 client
 * @summary Rotate client secret
 */
export const rotateClientSecret = (
  clientId: MaybeRef<string>,
  signal?: AbortSignal,
) => {
  clientId = unref(clientId);

  return customInstance<RotateClientSecret200>({
    url: `/api/clients/${clientId}/secret`,
    method: "POST",
    signal,
  });
};

export const getRotateClientSecretMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof rotateClientSecret>>,
    TError,
    { clientId: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof rotateClientSecret>>,
  TError,
  { clientId: string },
  TContext
> => {
  const mutationKey = ["rotateClientSecret"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof rotateClientSecret>>,
    { clientId: string }
  > = (props) => {
    const { clientId } = props ?? {};

    return rotateClientSecret(clientId);
  };

  return { mutationFn, ...mutationOptions };
};

export type RotateClientSecretMutationResult = NonNullable<
  Awaited<ReturnType<typeof rotateClientSecret>>
>;

export type RotateClientSecretMutationError = ErrorType<unknown>;

/**
 * @summary Rotate client secret
 */
export const useRotateClientSecret = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof rotateClientSecret>>,
      TError,
      { clientId: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof rotateClientSecret>>,
  TError,
  { clientId: string },
  TContext
> => {
  const mutationOptions = getRotateClientSecretMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
