export * from "./gen/generated.schemas";

export {
  getById1,
  getGetById1QueryKey,
  getGetById1QueryOptions,
  useGetById1,
  update2,
  getUpdate2MutationOptions,
  useUpdate2,
  delete1,
  getDelete1MutationOptions,
  useDelete1,
  getAll2,
  getGetAll2QueryKey,
  getGetAll2QueryOptions,
  useGetAll2,
  create1,
  getCreate1MutationOptions,
  useCreate1,
  useGetTree,
  getGetTreeQueryKey,
  getGetTreeQueryOptions,
} from "./gen/categories/categories";

export {
  revoke,
  getRevokeMutationOptions,
  useRevoke,
  getSharesByDocument,
  getGetSharesByDocumentQueryKey,
  getGetSharesByDocumentQueryOptions,
  useGetSharesByDocument,
  share,
  getShareMutationOptions,
  useShare,
  cleanupExpiredShares,
  getCleanupExpiredSharesMutationOptions,
  useCleanupExpiredShares,
  getSharesWithUser,
  getGetSharesWithUserQueryKey,
  getGetSharesWithUserQueryOptions,
  useGetSharesWithUser,
  getSharedWithMe,
  getGetSharedWithMeQueryKey,
  getGetSharedWithMeQueryOptions,
  useGetSharedWithMe,
} from "./gen/document-sharing/document-sharing";

export {
  getVersions,
  getGetVersionsQueryKey,
  getGetVersionsQueryOptions,
  useGetVersions,
  uploadVersion,
  getUploadVersionMutationOptions,
  useUploadVersion,
  getVersion,
  getGetVersionQueryKey,
  getGetVersionQueryOptions,
  useGetVersion,
  downloadVersion,
  getDownloadVersionQueryKey,
  getDownloadVersionQueryOptions,
  useDownloadVersion,
  getVersionDownloadUrl,
  getGetVersionDownloadUrlQueryKey,
  getGetVersionDownloadUrlQueryOptions,
  useGetVersionDownloadUrl,
} from "./gen/document-versions/document-versions";

export {
  getById,
  getGetByIdQueryKey,
  getGetByIdQueryOptions,
  useGetById,
  update,
  getUpdateMutationOptions,
  useUpdate,
  _delete,
  getDeleteMutationOptions,
  useDelete,
  getMetadata,
  getGetMetadataQueryKey,
  getGetMetadataQueryOptions,
  useGetMetadata,
  setMetadata,
  getSetMetadataMutationOptions,
  useSetMetadata,
  getAll1,
  getGetAll1QueryKey,
  getGetAll1QueryOptions,
  useGetAll1,
  upload,
  getUploadMutationOptions,
  useUpload,
  searchGet,
  getSearchGetQueryKey,
  getSearchGetQueryOptions,
  useSearchGet,
  search,
  getSearchMutationOptions,
  useSearch,
  download,
  getDownloadQueryKey,
  getDownloadQueryOptions,
  useDownload,
  getDownloadUrl,
  getGetDownloadUrlQueryKey,
  getGetDownloadUrlQueryOptions,
  useGetDownloadUrl,
  getPublic,
  getGetPublicQueryKey,
  getGetPublicQueryOptions,
  useGetPublic,
  getMyDocuments,
  getGetMyDocumentsQueryKey,
  getGetMyDocumentsQueryOptions,
  useGetMyDocuments,
  getByCategory,
  getGetByCategoryQueryKey,
  getGetByCategoryQueryOptions,
  useGetByCategory,
  deleteMetadataKey,
  getDeleteMetadataKeyMutationOptions,
  useDeleteMetadataKey,
} from "./gen/documents/documents";

export {
  getAll,
  getGetAllQueryKey,
  getGetAllQueryOptions,
  useGetAll,
  create,
  getCreateMutationOptions,
  useCreate,
  getById2,
  getGetById2QueryKey,
  getGetById2QueryOptions,
  useGetById2,
  delete2,
  getDelete2MutationOptions,
  useDelete2,
} from "./gen/tags/tags";
