/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * OAuth2 Authorization Server API
 * OAuth2 Authorization Server for Compta microservices. Provides token issuance and user authentication.
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from "@tanstack/vue-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationReturnType,
} from "@tanstack/vue-query";

import { unref } from "vue";
import type { MaybeRef } from "vue";

import type {
  IntrospectionRequest,
  IntrospectionResponse,
} from "../generated.schemas";

import { customInstance } from "../../../../api/axios-instance";
import type { ErrorType, BodyType } from "../../../../api/axios-instance";

/**
 * Introspect an OAuth2 token to get its metadata and validity status
 * @summary Introspect token
 */
export const introspect = (
  introspectionRequest: MaybeRef<IntrospectionRequest>,
  signal?: AbortSignal,
) => {
  introspectionRequest = unref(introspectionRequest);

  return customInstance<IntrospectionResponse>({
    url: `/oauth2/introspect`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: introspectionRequest,
    signal,
  });
};

export const getIntrospectMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof introspect>>,
    TError,
    { data: BodyType<IntrospectionRequest> },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof introspect>>,
  TError,
  { data: BodyType<IntrospectionRequest> },
  TContext
> => {
  const mutationKey = ["introspect"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof introspect>>,
    { data: BodyType<IntrospectionRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return introspect(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type IntrospectMutationResult = NonNullable<
  Awaited<ReturnType<typeof introspect>>
>;
export type IntrospectMutationBody = BodyType<IntrospectionRequest>;
export type IntrospectMutationError = ErrorType<unknown>;

/**
 * @summary Introspect token
 */
export const useIntrospect = <TError = ErrorType<unknown>, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof introspect>>,
      TError,
      { data: BodyType<IntrospectionRequest> },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationReturnType<
  Awaited<ReturnType<typeof introspect>>,
  TError,
  { data: BodyType<IntrospectionRequest> },
  TContext
> => {
  const mutationOptions = getIntrospectMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
