/**
 * Standardized error codes for the notification service
 * Format: SERVICE_CATEGORY_SPECIFIC_CODE
 * Example: NOTIF_USER_NOT_FOUND
 */
export enum ErrorCode {
  // User errors (USER_XXX)
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_EMAIL_NOT_FOUND = 'USER_EMAIL_NOT_FOUND',
  USER_PREFERENCES_NOT_FOUND = 'USER_PREFERENCES_NOT_FOUND',

  // Notification errors (NOTIF_XXX)
  NOTIF_NOT_FOUND = 'NOTIF_NOT_FOUND',
  NOTIF_INVALID_STATUS = 'NOTIF_INVALID_STATUS',
  NOTIF_SEND_FAILED = 'NOTIF_SEND_FAILED',
  NOTIF_QUEUE_FAILED = 'NOTIF_QUEUE_FAILED',

  // Template errors (TEMPLATE_XXX)
  TEMPLATE_NOT_FOUND = 'TEMPLATE_NOT_FOUND',
  TEMPLATE_INVALID_CODE = 'TEMPLATE_INVALID_CODE',
  TEMPLATE_COMPILATION_FAILED = 'TEMPLATE_COMPILATION_FAILED',
  TEMPLATE_LOAD_FAILED = 'TEMPLATE_LOAD_FAILED',

  // Email errors (EMAIL_XXX)
  EMAIL_SEND_FAILED = 'EMAIL_SEND_FAILED',
  EMAIL_INVALID_ADDRESS = 'EMAIL_INVALID_ADDRESS',
  EMAIL_BOUNCED = 'EMAIL_BOUNCED',
  EMAIL_COMPLAINT = 'EMAIL_COMPLAINT',

  // SMS errors (SMS_XXX)
  SMS_SEND_FAILED = 'SMS_SEND_FAILED',
  SMS_INVALID_PHONE = 'SMS_INVALID_PHONE',

  // SendPulse errors (SENDPULSE_XXX)
  SENDPULSE_API_ERROR = 'SENDPULSE_API_ERROR',
  SENDPULSE_AUTH_ERROR = 'SENDPULSE_AUTH_ERROR',
  SENDPULSE_RATE_LIMIT = 'SENDPULSE_RATE_LIMIT',

  // Validation errors (VALIDATION_XXX)
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  VALIDATION_MISSING_FIELD = 'VALIDATION_MISSING_FIELD',
  VALIDATION_INVALID_TYPE = 'VALIDATION_INVALID_TYPE',
  VALIDATION_INVALID_ENUM = 'VALIDATION_INVALID_ENUM',

  // Queue errors (QUEUE_XXX)
  QUEUE_CONNECTION_FAILED = 'QUEUE_CONNECTION_FAILED',
  QUEUE_JOB_FAILED = 'QUEUE_JOB_FAILED',
  QUEUE_RETRY_EXHAUSTED = 'QUEUE_RETRY_EXHAUSTED',

  // Database errors (DB_XXX)
  DB_CONNECTION_FAILED = 'DB_CONNECTION_FAILED',
  DB_QUERY_FAILED = 'DB_QUERY_FAILED',
  DB_CONSTRAINT_VIOLATION = 'DB_CONSTRAINT_VIOLATION',

  // External service errors (EXTERNAL_XXX)
  EXTERNAL_SERVICE_UNAVAILABLE = 'EXTERNAL_SERVICE_UNAVAILABLE',
  EXTERNAL_SERVICE_TIMEOUT = 'EXTERNAL_SERVICE_TIMEOUT',

  // Authorization errors (AUTH_XXX)
  AUTH_MISSING_HEADERS = 'AUTH_MISSING_HEADERS',
  AUTH_INVALID_ROLES = 'AUTH_INVALID_ROLES',
  AUTH_FORBIDDEN = 'AUTH_FORBIDDEN',

  // General errors (GENERAL_XXX)
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  NOT_FOUND = 'NOT_FOUND',
}
